const EmpDetails = {
  headers: {
    name: "Employee Name",
    id: "Employee ID",
    empJD: "Joining Date",
    role: "Role",
    empStat: "Status",
    empExp: "Experience",
    empAct: "Action",
    address: "Address",
    empEmail: "Email",
  },
  details: [
    {
      name: "Harry",
      id: 1,
      empJD: "12.02.24",
      role: "Full Stack",
      empStat: "Probation",
      empExp: 5,
      address: "Location 1",
      email: "harry@example.com",
    },
    {
      name: "Susan Kurian",
      id: 2,
      empJD: "12.02.24",
      role: "UI Engineer",
      empStat: "Probation",
      empExp: 5,
      address: "Location 1",
      email: "susan.kurian@example.com",
    },
    {
      name: "Susan Kurian",
      id: 3,
      empJD: "12.02.24",
      role: "UI Engineer",
      empStat: "Active",
      empExp: 5,
      address: "Location 1",
      email: "susan.kurian@example.com",
    },
    {
      name: "Susan Kurian",
      id: 4,
      empJD: "12.02.24",
      role: "UI Engineer",
      empStat: "Inactive",
      empExp: 5,
      address: "Location 1",
      email: "susan.kurian@example.com",
    },
  ],
};

export default EmpDetails;
